packages:
  - 'apps/app'
  - 'apps/app-frontend'
  - 'packages/api-client'
  - 'packages/app-lib'
  - 'packages/ariadne'
  - 'packages/assets'
  - 'packages/daedalus'
  - 'packages/path-util'
  - 'packages/tooling-config'
  - 'packages/ui'
  - 'packages/utils'
