ALTER TABLE settings ADD COLUMN proxy_enabled INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN proxy_type TEXT NOT NULL DEFAULT 'http';
ALTER TABLE settings ADD COLUMN proxy_host TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN proxy_port INTEGER NOT NULL DEFAULT 8080;
ALTER TABLE settings ADD COLUMN proxy_auth_enabled INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN proxy_username TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN proxy_password TEXT NOT NULL DEFAULT '';
